services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - ".env"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  

volumes:
  postgres_data: